{
'id': 'bugs.core_870',
'qmid': 'bugs.core_870',
'tracker_id': 'CORE-870',
'title': 'Engine crashes while trying to backup a logically corrupt db',
'description': '',
'versions': [
{
 'firebird_version': '2.1',
 'platform': 'All',
 'database': 'Existing',
 'database_name': 'core870.fdb',
 'test_type': 'Python',
 'test_script': """import os

print 'Starting backup...'
fbk = os.path.join(context['temp_directory'],'backup.fbk')
runProgram('gbak',['-b','-user',user_name,'-password',user_password,dsn,fbk])
print 'gbak finished...'
if os.path.isfile(fbk):
    print 'Delete backup file...'
    os.remove(fbk)
    print 'Backup file deleted.'
""",
 'expected_stdout': """Starting backup...
gbak finished...
Delete backup file...
Backup file deleted.
"""
}
]
}
